@extends('layouts.main')
@section('styles')
	<link rel="stylesheet" href="{{ asset('css/website-index.css') }}">
@endsection
@section('content')
<section class="sss">
	<div class="container">
		<div class="row">
			<h1 class="title">KULLANIM ŞARTLARI VE İNTERNET SİTESİ ÜYELİK SÖZLEŞMESİ</h1>
		</div>
		<div class="row questions sozlesme" style="height:auto;">
			<p>
				<b>Sözleşmenin Tarafları:</b><br/><br/>
				İş bu Sözleşme;<br/><br/>
				a) www.dugunhediyem.net internet sitesi üzerinden faaliyette bulunan Harbiye, Atiye Sokak No:8, 34367 Şişli / İSTANBUL adresinde mukim DÜĞÜN HEDİYEM A.Ş. (bundan böyle sözleşme içerisinde "DÜĞÜN HEDİYEM" olarak kısaltılacaktır) ile<br/><br/>
				b) www.dugunhediyem.net internet sitesine üye olan, üyelik sayfasında kendisi tarafından belirtilecek adreste mukim internet kullanıcısı (bundan böyle sözleşme içerisinde "Üye" olarak kısaltılacaktır) arasında mutabakat ile kabul edilmiştir.<br/><br/>
				<b>2. Sözleşmenin Konusu:</b><br/><br/>
				İşbu Sözleşme www.dugunhediyem.net internet sitesinden ve belirtilen şartlar ve ücretler mukabilinde DÜĞÜN HEDİYEM tarafından sunulan hizmetlerden, satışa arz edilmiş ürünlerden, üyeye özel ayrıcalıklardan üyenin faydalanması hususlarını düzenlemektedir.  <br/><br/>
				<b>3. Sözleşmenin Hükümleri:</b><br/><br/>
				3.1. İş bu sözleşmede açık bir şekilde taahhüt edilmemiş hiçbir hususu DÜĞÜN HEDİYEM aleyhine varmış gibi yorumlanamaz. Aksi DÜĞÜN HEDİYEM tarafından yazılı olarak belirtilmediği sürece DÜĞÜN HEDİYEM, sitede yer alan ürün ve hizmetler için sitede ilan edilen ücretleri talep etme hakkına sahip olacaktır.<br/><br/>
				3.2. İş bu üyelik sözleşmesi, Üye’ ye herhangi bir maddi taahhüt yada yükümlülük getirmemektedir. Üye ancak  www.dugunhediyem.net web adresinden sipariş edeceği ürün ve hizmetlerin bedelleri ile buna ilişkin sair ücretleri ödemekle yükümlü olacaktır.  Üyelik için ayrıca herhangi bir ücret taahhüt ettirilmeyecektir.<br/><br/>
				3.3. DÜĞÜN HEDİYEM, iş bu sözleşmenin imzasından sonra üyelik ve sair adlar altında iş bu sözleşme tarafı üye’ ye verilmiş haklardan, üyelik özelliklerinden daha geniş nitelikli, daha farklı özellikli, ayrıcalıklar, indirim hakları içeren, ücretli yada sair taahhütlere havi üyelik çeşitleri ihdas edebilir. Bu halde Üye’nin rızası olmaksızın üyeliği ücretli olarak değiştirilmeyecek ancak üye, ücretli üyelik özelliklerinden üyeliğini yükseltmeksizin yada yararlanmak istediği hizmet ve ayrıcalıkları ihtiva eden üyeliğini aktifleştirmeksizin yeni ve ücretli hizmetlerden yararlandırılmasını talep edemeyecektir.<br/><br/>
				3.4. Üye, www.dugunhediyem.net   internet sitesine üye olurken verdiği kişisel ve diğer sair bilgilerin kanunlar önünde doğru olduğunu, DÜĞÜN HEDİYEM'in bu bilgilerin gerçeğe aykırılığı nedeniyle uğrayacağı tüm zararları tazmin edeceğini beyan ve taahhüt eder.<br/><br/>
				3.5. Üye, www.dugunhediyem.net  internet sitesine üye olurken kendisine verilmiş olan şifreyi başka kişi ya da kuruluşlara veremez, üyenin söz konusu şifreyi kullanma hakkı bizzat kendisine aittir. Bu sebeple doğabilecek tüm sorumluluk ile üçüncü kişiler veya yetkili merciler tarafından DÜĞÜN HEDİYEM'e karşı ileri sürülebilecek tüm iddia ve taleplere karşı, DÜĞÜN HEDİYEM'in söz konusu izinsiz kullanımdan kaynaklanan her türlü tazminat ve sair talep hakkı saklıdır.<br/><br/>
				3.6. Üye, www.dugunhediyem.net   internet sitesinde mevcut üyelere özel hizmetlerden faydalanırken yasal mevzuat hükümlerine riayet etmeyi ve bunları ihlal etmemeyi baştan kabul ve taahhüt eder. Aksi takdirde, doğacak tüm hukuki ve cezai yükümlülükler tamamen ve münhasıran üyeyi bağlayacaktır.<br/><br/>
				3.7. Üye, www.dugunhediyem.net   internet sitesini ve portal hizmetlerini ve hiçbir şekilde kamu düzenini bozucu, genel ahlaka aykırı, başkalarını rahatsız ve taciz edici şekilde, yasalara aykırı bir amaç için, başkalarının fikri ve telif haklarına tecavüz edecek şekilde kullanamaz, almakta olduğu hizmetleri 3.şahısların kullanımına sunamaz, kiralama veya satışa arz etme gibi ticari faaliyetlere konu edemez. Ayrıca, üye başkalarının hizmetleri kullanmasını önleyici veya zorlaştırıcı faaliyet (spam, virus, truva atı, vb.) ve işlemlerde bulunamaz.<br/><br/>
				3.8. www.dugunhediyem.net   internet sitesinde üyeler tarafından beyan edilen, yazılan, kullanılan fikir ve düşünceler, tamamen üyelerin kendi kişisel görüşleridir ve görüş sahibini bağlar. Bu görüş ve düşüncelerin DÜĞÜN HEDİYEM ile hiçbir ilgi ve bağlantısı yoktur. DÜĞÜN HEDİYEM'in üyenin beyan edeceği fikir ve görüşler nedeniyle üçüncü kişilerin uğrayabileceği zararlardan ve hizmetlerin kullanımı esnasında Müşteri’nin uğrayabileceği üçüncü kişilerin fiil ve hareketlerinden doğabilecek zararlardan dolayı herhangi bir sorumluluğu bulunmamaktadır.<br/><br/>
				3.9. DÜĞÜN HEDİYEM, üye verilerinin yetkisiz kişilerce okunmasından ve üye yazılım ve verilerine gelebilecek zararlardan dolayı sorumlu olmayacaktır. Üye, www.dugunhediyem.net  internet sitesinin ve portal hizmetlerinin kullanılmasından dolayı uğrayabileceği herhangi bir zarar yüzünden DÜĞÜN HEDİYEM'den tazminat talep etmemeyi peşinen kabul etmiştir.<br/><br/>
				3.10. Üye, diğer internet kullanıcılarının yazılımlarına ve verilerine izinsiz olarak ulaşmamayı veya bunları kullanmamayı kabul etmiştir. Aksi takdirde, bundan doğacak hukuki ve cezai sorumluluklar tamamen üyeye aittir.<br/><br/>
				3.11. İşbu üyelik sözleşmesi içerisinde sayılan maddelerden bir ya da birkaçını ihlal eden üye işbu ihlal nedeniyle cezai ve hukuki olarak şahsen sorumlu olup, DÜĞÜN HEDİYEM'i bu ihlallerin hukuki ve cezai sonuçlarından ari tutacaktır. Ayrıca; işbu ihlal nedeniyle, olayın hukuk alanına intikal ettirilmesi halinde, DÜĞÜN HEDİYEM'in üyeye karşı üyelik sözleşmesine uyulmamasından dolayı tazminat talebinde bulunma hakkı saklıdır.<br/><br/>
				3.12. DÜĞÜN HEDİYEM'in her zaman tek taraflı olarak gerektiğinde üyenin üyeliğini silme, müşteriye ait dosya, belge ve bilgileri silme hakkı vardır. Üye işbu tasarrufu önceden kabul eder. Bu durumda, DÜĞÜN HEDİYEM'in hiçbir sorumluluğu yoktur.<br/><br/>
				3.13. DÜĞÜN HEDİYEM,  www.dugunhediyem.net  internet sitesinde yer alan her türlü bilginin doğruluğu, eksiksiz olması, yeterliliği ve güncelliği hiçbir surette DÜĞÜN HEDİYEM tarafından garanti ve taahhüt edilmemektedir. Kullanıcı hiçbir şekilde web sitesi' nde yer alan bilgilerin ve/veya portal hizmetlerinin hatalı olduğu yada bu bilgilere istinaden zarara uğradığı iddiasında bulunamaz. DÜĞÜN HEDİYEM hiçbir şekil ve surette ön ihbara ve/veya ihtara gerek kalmaksızın her zaman söz konusu bilgileri ve/veya portal hizmetlerini değiştirebilir, düzeltebilir ve/veya çıkarabilir. DÜĞÜN HEDİYEM web sitesinin ve portal hizmetlerinin hatasız olması için her türlü tedbiri almıştır. Bununla birlikte sitede mevcut yada oluşabilecek hatalar ile ilgili herhangi bir garanti verilmemektedir.<br/><br/>
				3.14. Bu www.dugunhediyem.net  internet sitesine erişimden, sitede yer alan bilgilerin, hizmetlerin gerek doğrudan gerekse dolaylı kullanımından kaynaklanan doğrudan ve/veya dolaylı maddi ve/veya manevi menfi ve/veya müsbet, velhasıl her türlü zarardan her nam altında olursa olsun DÜĞÜN HEDİYEM, yönetim kurulu üyeleri, yöneticileri, çalışanları, bu sitede yer alan bilgileri ve/veya portal hizmetlerini hazırlayan kişiler sorumlu tutulamaz.<br/><br/>
				3.15. www.dugunhediyem.net internet sitesinde yer alan, bunları içeren ama bunlarla sınırlı olmayan tüm malzeme ve dokümanlar münhasıran DÜĞÜN HEDİYEM mülkiyetinde olup, bu malzeme ve dokümanlara ilişkin telif hakkı ve/veya diğer fikri ve sınai mülkiyet hakları ilgili kanunlarca korunmakta olup, bu malzemeler ve dokümanlar üye tarafından izinsiz kullanılamaz, iktisap edilemez ve değiştirilemez. Bu web sitesinde adı geçen başkaca şirketler ve ürünleri sahiplerinin ticari markalarıdır ve ayrıca fikri mülkiyet hakları kapsamında korunmaktadır.<br/><br/>
				3.16.  www.dugunhediyem.net internet sitesinde malzemeler ve dokümanlar hiç bir surette üye tarafından değiştirilemez, kopyalanamaz, çoğaltılamaz ve yeniden yayınlanamaz.<br/><br/>
				3.17. DÜĞÜN HEDİYEM tarafından www.dugunhediyem.net internet sitesinin iyileştirilmesi, geliştirilmesine yönelik olarak ve/veya yasal mevzuat çerçevesinde siteye erişmek için kullanılan Internet servis sağlayıcısının adı ve Internet Protokol (IP) adresi, siteye erişilen tarih ve saat, sitede bulunulan sırada erişilen sayfalar ve siteye doğrudan bağlanılmasını sağlayan Web sitesinin Internet adresi gibi birtakım bilgiler toplanabilir.<br/><br/>
				3.18. DÜĞÜN HEDİYEM kullanıcılarına daha iyi hizmet sunmak, ürünlerini ve hizmetlerini iyileştirmek, sitenin kullanımını kolaylaştırmak için kullanımını kullanıcılarının özel tercihlerine ve ilgi alanlarına yönelik çalışmalarda üyelerin kişisel bilgilerini kullanabilir. DÜĞÜN HEDİYEM, üyenin portal hizmetlerini alırken  www.dugunhediyem.net  internet sitesi üzerinde yaptığı hareketlerin kaydını bulundurma hakkını saklı tutar.<br/><br/>
				3.19. DÜĞÜN HEDİYEM, üyenin kişisel bilgilerini yasal bir zorunluluk olarak istendiğinde veya (a)yasal gereklere uygun hareket etmek veya DÜĞÜN HEDİYEM ya da DÜĞÜN HEDİYEM sitesine tebliğ edilen yasal işlemlere uymak; (b) DÜĞÜN HEDİYEM ve DÜĞÜN HEDİYEM web sitesi ailesinin haklarını ve mülkiyetini korumak ve savunmak için gerekli olduğuna iyi niyetle kanaat getirdiği hallerde açıklayabilir.<br/><br/>
				3.20. DÜĞÜN HEDİYEM web sitesinin virüs ve benzeri amaçlı yazılımlardan arındırılmış olması için mevcut imkanlar dahilinde tedbir alınmıştır. Bunun yanında nihai güvenliğin sağlanması için kullanıcının, kendi virüs koruma sistemini tedarik etmesi ve gerekli korunmayı sağlaması gerekmektedir. Bu bağlamda üye DÜĞÜN HEDİYEM web sitesi' ne girmesiyle, kendi yazılım ve işletim sistemlerinde oluşabilecek tüm hata ve bunların doğrudan yada dolaylı sonuçlarından kendisinin sorumlu olduğunu kabul etmiş sayılır.<br/><br/>
				3.20. DÜĞÜN HEDİYEM web sitesinin virüs ve benzeri amaçlı yazılımlardan arındırılmış olması için mevcut imkanlar dahilinde tedbir alınmıştır. Bunun yanında nihai güvenliğin sağlanması için kullanıcının, kendi virüs koruma sistemini tedarik etmesi ve gerekli korunmayı sağlaması gerekmektedir. Bu bağlamda üye DÜĞÜN HEDİYEM web sitesi' ne girmesiyle, kendi yazılım ve işletim sistemlerinde oluşabilecek tüm hata ve bunların doğrudan yada dolaylı sonuçlarından kendisinin sorumlu olduğunu kabul etmiş sayılır.<br/><br/>
				3.22. DÜĞÜN HEDİYEM, üyelik sözleşmesinin koşullarını hiçbir şekil ve surette ön ihbara ve/veya ihtara gerek kalmaksızın her zaman değiştirebilir, güncelleyebilir veya iptal edebilir. Değiştirilen, güncellenen yada yürürlükten kaldırılan her hüküm, yayın tarihinde tüm üyeler bakımından hüküm ifade edecektir.<br/><br/>
				3.23. Taraflar, DÜĞÜN HEDİYEM'e ait tüm bilgisayar kayıtlarının tek ve gerçek münhasır delil olarak, HUMK madde 287'ye uygun şekilde esas alınacağını ve söz konusu kayıtların bir delil sözleşmesi teşkil ettiği hususunu kabul ve beyan eder.
				<b>4. Sözleşmenin Süresi ve Feshi:</b><br/><br/>
				İş bu sözleşme Üye tarafından kabul edildiğini beyan ile yürürlüğe girer. DÜĞÜN HEDİYEM sözleşmeyi üye’ ye arz ederek kabul edilmiş sayılmakla birlikte Üye tarafından onaylanmamış sözleşmeler DÜĞÜN HEDİYEM’e karşı kullanılamayacaktır. <br/><br/>
				İşbu sözleşme üyenin üyeliğini iptal etmesi veya DÜĞÜN HEDİYEM tarafından üyeliğinin iptal edilmesine kadar yürürlükte kalacaktır. DÜĞÜN HEDİYEM üyenin üyelik sözleşmesinin herhangi bir hükmünü ihlal etmesi durumunda üyenin üyeliğini iptal ederek sözleşmeyi tek taraflı olarak feshedebilecektir.<br/><br/>
				<b>5. Anlaşmazlıkların Çözümü:</b><br/><br/>
				İşbu sözleşmeye ilişkin ihtilaflarda İstanbul Mahkemeleri ve İcra Daireleri yetkilidir.<br/><br/>
				<b>6. Yürürlük:</b><br/><br/>
				Üyenin, üyelik kaydı yapması üyenin üyelik sözleşmesinde yer alan tüm maddeleri okuduğu ve üyelik sözleşmesinde yer alan maddeleri kabul ettiği anlamına gelir. İşbu Sözleşme üyenin üye olması anında akdedilmiş ve karşılıklı olarak yürürlüğe girmiştir. Üye tarafından elektronik ortamda onay verilmiş olması yeterli olup, ayrıca üyenin imzası aranmayacaktır.
			</p>
		</div>

	</div>
</section>
@endsection
